/**
 * Demo content for the platform.
 *
 * IMPORTANT / ACADEMIC HONESTY
 * ---------------------------------------------------------------------------
 * Every opportunity below is FICTIONAL. The organisations, deadlines, stipends
 * and links were written for this semester project so the platform can be
 * demonstrated with realistic-looking data.
 *
 * Each row is stored with is_demo = TRUE and the user interface shows a
 * "Sample" badge on it, so nobody mistakes the demo catalogue for real
 * listings. When you add genuine opportunities through the admin panel,
 * leave "Mark as sample data" unchecked and no badge appears.
 *
 * Deadlines are written as "days from today" so the demo never looks expired,
 * no matter when you run the seed script.
 */

/** Returns a YYYY-MM-DD date a given number of days from today. */
export function daysFromNow(days) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------
export const CATEGORIES = [
  {
    name: 'Internship',
    slug: 'internship',
    icon: 'Briefcase',
    color: 'blue',
    description: 'Paid and unpaid work experience with companies and research labs.',
  },
  {
    name: 'Scholarship',
    slug: 'scholarship',
    icon: 'GraduationCap',
    color: 'emerald',
    description: 'Financial support for tuition, living costs and study abroad.',
  },
  {
    name: 'Hackathon',
    slug: 'hackathon',
    icon: 'Code2',
    color: 'violet',
    description: 'Build a working project in 24-48 hours and win prizes.',
  },
  {
    name: 'Competition',
    slug: 'competition',
    icon: 'Trophy',
    color: 'amber',
    description: 'Case studies, coding contests and data science challenges.',
  },
  {
    name: 'Course',
    slug: 'course',
    icon: 'BookOpen',
    color: 'sky',
    description: 'Certified online and offline courses to build new skills.',
  },
  {
    name: 'Workshop',
    slug: 'workshop',
    icon: 'Presentation',
    color: 'rose',
    description: 'Short hands-on sessions run by industry practitioners.',
  },
  {
    name: 'Fellowship',
    slug: 'fellowship',
    icon: 'Award',
    color: 'indigo',
    description: 'Long-term funded programmes for research and social impact.',
  },
  {
    name: 'Career Program',
    slug: 'career-program',
    icon: 'Rocket',
    color: 'teal',
    description: 'Mentorship, placement preparation and early-career pipelines.',
  },
];

// ---------------------------------------------------------------------------
// Skills  (the master list the onboarding tag input suggests from)
// ---------------------------------------------------------------------------
export const SKILLS = [
  { name: 'Python', category: 'Programming' },
  { name: 'Java', category: 'Programming' },
  { name: 'C++', category: 'Programming' },
  { name: 'JavaScript', category: 'Programming' },
  { name: 'TypeScript', category: 'Programming' },
  { name: 'React', category: 'Web' },
  { name: 'Node.js', category: 'Web' },
  { name: 'HTML/CSS', category: 'Web' },
  { name: 'SQL', category: 'Data' },
  { name: 'Machine Learning', category: 'Data' },
  { name: 'Deep Learning', category: 'Data' },
  { name: 'Data Science', category: 'Data' },
  { name: 'Data Analysis', category: 'Data' },
  { name: 'Statistics', category: 'Data' },
  { name: 'Pandas', category: 'Data' },
  { name: 'NumPy', category: 'Data' },
  { name: 'TensorFlow', category: 'Data' },
  { name: 'PyTorch', category: 'Data' },
  { name: 'Power BI', category: 'Data' },
  { name: 'Excel', category: 'Data' },
  { name: 'Tableau', category: 'Data' },
  { name: 'Cloud Computing', category: 'Infrastructure' },
  { name: 'AWS', category: 'Infrastructure' },
  { name: 'Docker', category: 'Infrastructure' },
  { name: 'Linux', category: 'Infrastructure' },
  { name: 'Cybersecurity', category: 'Security' },
  { name: 'Networking', category: 'Security' },
  { name: 'Android', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'UI/UX', category: 'Design' },
  { name: 'Figma', category: 'Design' },
  { name: 'Graphic Design', category: 'Design' },
  { name: 'Communication', category: 'Soft Skill' },
  { name: 'Teamwork', category: 'Soft Skill' },
  { name: 'Problem Solving', category: 'Soft Skill' },
  { name: 'Public Speaking', category: 'Soft Skill' },
  { name: 'Marketing', category: 'Business' },
  { name: 'Finance', category: 'Business' },
  { name: 'Business Analysis', category: 'Business' },
  { name: 'Research Writing', category: 'Academic' },
  { name: 'Algorithms', category: 'Programming' },
  { name: 'Data Structures', category: 'Programming' },
  { name: 'Git', category: 'Programming' },
  { name: 'Robotics', category: 'Engineering' },
  { name: 'IoT', category: 'Engineering' },
  { name: 'CAD', category: 'Engineering' },
];

// ---------------------------------------------------------------------------
// Interests
// ---------------------------------------------------------------------------
export const INTERESTS = [
  'Artificial Intelligence',
  'Data Science',
  'Web Development',
  'Cybersecurity',
  'Cloud Computing',
  'Mobile Development',
  'Research',
  'Entrepreneurship',
  'Finance',
  'Design',
  'Robotics',
  'Open Source',
  'Product Management',
  'Social Impact',
  'Game Development',
];

// ---------------------------------------------------------------------------
// Opportunities  (all fictional -- see the note at the top of this file)
// ---------------------------------------------------------------------------
export const OPPORTUNITIES = [
  // ---------------------------- INTERNSHIPS --------------------------------
  {
    title: 'Machine Learning Engineering Internship',
    organization: 'Nimbus AI Labs',
    category: 'internship',
    description:
      'Join the applied research team and help build recommendation models that serve millions of requests every day. You will clean datasets, train baseline models, run evaluation experiments and present your findings in weekly research reviews. Mentorship is provided by a senior ML engineer throughout the programme.',
    eligibility: '2nd, 3rd or final year students of B.Tech / B.E. / B.Sc in CS, IT, Data Science or AI/ML.',
    benefits: 'Monthly stipend, pre-placement offer for top performers, certificate and letter of recommendation.',
    location: 'Bengaluru',
    mode: 'Hybrid',
    duration: '6 months',
    stipend: 'INR 45,000 / month',
    deadlineIn: 24,
    applicationUrl: 'https://example.com/nimbus-ai/ml-internship',
    source: 'Nimbus AI Labs careers page (sample)',
    skills: ['Python', 'Machine Learning', 'SQL', 'PyTorch', 'Statistics'],
  },
  {
    title: 'Data Science Summer Internship',
    organization: 'Vector Analytics',
    category: 'internship',
    description:
      'A structured 10-week summer internship for students who want hands-on experience with real business data. Interns work on churn prediction, customer segmentation and dashboard building, and finish the programme with a capstone presentation to the analytics leadership team.',
    eligibility: 'Students in the 3rd or final year of any engineering or statistics degree.',
    benefits: 'Stipend, industry mentor, capstone project certificate.',
    location: 'Pune',
    mode: 'On-site',
    duration: '10 weeks',
    stipend: 'INR 30,000 / month',
    deadlineIn: 18,
    applicationUrl: 'https://example.com/vector-analytics/summer-internship',
    source: 'Vector Analytics campus programme (sample)',
    skills: ['Python', 'SQL', 'Data Analysis', 'Pandas', 'Power BI', 'Statistics'],
  },
  {
    title: 'Full Stack Web Development Internship',
    organization: 'Kairo Technologies',
    category: 'internship',
    description:
      'Work alongside the product engineering team on a React and Node.js codebase used by 200+ client organisations. You will ship real features, take part in code reviews and learn how a production deployment pipeline works from commit to release.',
    eligibility: 'Any undergraduate student with demonstrable web development projects on GitHub.',
    benefits: 'Remote-first stipend, flexible hours, mentorship, certificate.',
    location: 'Remote',
    mode: 'Remote',
    duration: '4 months',
    stipend: 'INR 25,000 / month',
    deadlineIn: 12,
    applicationUrl: 'https://example.com/kairo/fullstack-internship',
    source: 'Kairo Technologies internship portal (sample)',
    skills: ['React', 'Node.js', 'JavaScript', 'SQL', 'Git', 'HTML/CSS'],
  },
  {
    title: 'Cybersecurity Analyst Internship',
    organization: 'Sentinel Secure',
    category: 'internship',
    description:
      'Support the security operations centre with log analysis, vulnerability triage and incident documentation. Interns rotate through blue-team monitoring and basic penetration testing exercises in a controlled lab environment, and receive training on industry tooling.',
    eligibility: 'Final year students in CS, IT or Electronics with an interest in security.',
    benefits: 'Stipend, security certification voucher, full-time conversion opportunity.',
    location: 'Hyderabad',
    mode: 'On-site',
    duration: '6 months',
    stipend: 'INR 35,000 / month',
    deadlineIn: 33,
    applicationUrl: 'https://example.com/sentinel-secure/soc-internship',
    source: 'Sentinel Secure careers (sample)',
    skills: ['Cybersecurity', 'Networking', 'Linux', 'Python', 'Problem Solving'],
  },
  {
    title: 'Cloud Infrastructure Internship',
    organization: 'Stratos Cloud Services',
    category: 'internship',
    description:
      'Learn how large-scale cloud systems are built and operated. You will write infrastructure-as-code, containerise internal services and help improve deployment reliability. The programme includes a funded cloud practitioner certification attempt.',
    eligibility: 'Students in the 3rd or final year of B.Tech / B.E. / MCA.',
    benefits: 'Stipend, certification voucher, dedicated mentor.',
    location: 'Remote',
    mode: 'Remote',
    duration: '5 months',
    stipend: 'INR 32,000 / month',
    deadlineIn: 41,
    applicationUrl: 'https://example.com/stratos/cloud-internship',
    source: 'Stratos Cloud Services (sample)',
    skills: ['AWS', 'Docker', 'Linux', 'Cloud Computing', 'Git'],
  },
  {
    title: 'Product Design (UI/UX) Internship',
    organization: 'Loop Studio',
    category: 'internship',
    description:
      'A design internship for students who enjoy turning messy problems into clean interfaces. You will run user interviews, build wireframes and high-fidelity prototypes in Figma, and contribute to the studio design system used across client projects.',
    eligibility: 'Any student with a portfolio of design work. Degree and branch are not restricted.',
    benefits: 'Stipend, portfolio review, design community membership.',
    location: 'Mumbai',
    mode: 'Hybrid',
    duration: '3 months',
    stipend: 'INR 20,000 / month',
    deadlineIn: 15,
    applicationUrl: 'https://example.com/loop-studio/design-internship',
    source: 'Loop Studio (sample)',
    skills: ['UI/UX', 'Figma', 'Graphic Design', 'Communication'],
  },
  {
    title: 'Android Development Internship',
    organization: 'Meridian Mobile',
    category: 'internship',
    description:
      'Build and ship features for a consumer Android application with over half a million installs. Interns own small features end to end, from design review through testing and release, and learn mobile performance profiling along the way.',
    eligibility: 'Students in the 2nd year or above with at least one published or demo-ready mobile app.',
    benefits: 'Stipend, Play Store credit, mentorship.',
    location: 'Remote',
    mode: 'Remote',
    duration: '4 months',
    stipend: 'INR 22,000 / month',
    deadlineIn: 27,
    applicationUrl: 'https://example.com/meridian/android-internship',
    source: 'Meridian Mobile (sample)',
    skills: ['Android', 'Java', 'Git', 'Problem Solving'],
  },
  {
    title: 'Business Analyst Internship',
    organization: 'Northline Consulting',
    category: 'internship',
    description:
      'Work with consulting teams on market sizing, competitor research and client dashboards. This internship suits students who like structured problem solving and want exposure to how business decisions are supported by data.',
    eligibility: 'Students of any degree in their pre-final or final year. MBA students also welcome.',
    benefits: 'Stipend, client exposure, recommendation letter.',
    location: 'Delhi',
    mode: 'Hybrid',
    duration: '3 months',
    stipend: 'INR 28,000 / month',
    deadlineIn: 36,
    applicationUrl: 'https://example.com/northline/ba-internship',
    source: 'Northline Consulting (sample)',
    skills: ['Excel', 'Business Analysis', 'Communication', 'Data Analysis', 'Finance'],
  },

  // ---------------------------- SCHOLARSHIPS -------------------------------
  {
    title: 'Aarna Merit Scholarship for Engineering Students',
    organization: 'Aarna Education Foundation',
    category: 'scholarship',
    description:
      'A merit-cum-means scholarship supporting engineering students from families with limited income. The award covers a significant share of annual tuition and is renewable each year subject to academic performance.',
    eligibility: 'B.Tech / B.E. students with 70% or above in the previous year and family income under INR 6 lakh per annum.',
    benefits: 'Up to INR 75,000 per year, renewable for the full degree.',
    location: 'India',
    mode: 'Remote',
    duration: 'Annual, renewable',
    stipend: 'INR 75,000 / year',
    deadlineIn: 45,
    applicationUrl: 'https://example.com/aarna-foundation/merit-scholarship',
    source: 'Aarna Education Foundation (sample)',
    skills: ['Research Writing', 'Communication'],
  },
  {
    title: 'Women in Technology Scholarship',
    organization: 'Lumen Tech Trust',
    category: 'scholarship',
    description:
      'A scholarship created to increase the number of women completing technology degrees. Along with the financial award, every recipient is paired with a working professional in her field of interest for a year of mentorship.',
    eligibility: 'Women students enrolled in any technology or computing degree, 1st year onwards.',
    benefits: 'INR 1,00,000 award, one-year mentorship, alumni network access.',
    location: 'India',
    mode: 'Remote',
    duration: 'One-time award',
    stipend: 'INR 1,00,000',
    deadlineIn: 29,
    applicationUrl: 'https://example.com/lumen-trust/women-in-tech',
    source: 'Lumen Tech Trust (sample)',
    skills: ['Communication', 'Problem Solving'],
  },
  {
    title: 'Data Science Excellence Scholarship',
    organization: 'Quantify Academy',
    category: 'scholarship',
    description:
      'Awarded on the basis of a short data challenge rather than marks alone. Applicants analyse a provided dataset and submit a two-page report; the strongest submissions receive a full fee waiver for the academy professional certificate.',
    eligibility: 'Students of Data Science, Statistics, CS or any quantitative branch, 2nd year onwards.',
    benefits: 'Full course fee waiver worth INR 60,000 plus a capstone mentor.',
    location: 'India',
    mode: 'Remote',
    duration: 'One-time award',
    stipend: 'INR 60,000 fee waiver',
    deadlineIn: 21,
    applicationUrl: 'https://example.com/quantify/ds-scholarship',
    source: 'Quantify Academy (sample)',
    skills: ['Python', 'Statistics', 'Data Analysis', 'Research Writing', 'Pandas'],
  },
  {
    title: 'Rural Innovators Study Grant',
    organization: 'Grameen Vikas Trust',
    category: 'scholarship',
    description:
      'A study grant for students from rural districts who are the first in their family to attend university. The grant covers hostel fees, a laptop and an internet allowance for the academic year.',
    eligibility: 'First-generation university students from a rural district, any degree, 1st or 2nd year.',
    benefits: 'Hostel fee support, laptop, annual internet allowance.',
    location: 'India',
    mode: 'Remote',
    duration: 'Academic year',
    stipend: 'INR 50,000 + laptop',
    deadlineIn: 52,
    applicationUrl: 'https://example.com/grameen-vikas/study-grant',
    source: 'Grameen Vikas Trust (sample)',
    skills: ['Communication'],
  },
  {
    title: 'Global Exchange Semester Scholarship',
    organization: 'Meridian International Education',
    category: 'scholarship',
    description:
      'Funds one exchange semester at a partner university abroad. The scholarship covers tuition difference, visa costs and a monthly living allowance, and includes pre-departure orientation sessions.',
    eligibility: 'Students in the 2nd or 3rd year with a minimum 7.5 CGPA and English proficiency.',
    benefits: 'Tuition support, travel grant, monthly living allowance.',
    location: 'International',
    mode: 'On-site',
    duration: 'One semester',
    stipend: 'Up to INR 4,00,000 total support',
    deadlineIn: 60,
    applicationUrl: 'https://example.com/meridian-intl/exchange-scholarship',
    source: 'Meridian International Education (sample)',
    skills: ['Communication', 'Research Writing', 'Public Speaking'],
  },

  // ---------------------------- HACKATHONS ---------------------------------
  {
    title: 'BuildAI 36-Hour National Hackathon',
    organization: 'CodeCrafters Community',
    category: 'hackathon',
    description:
      'A 36-hour national hackathon where teams build an AI-powered product from scratch. Tracks include healthcare, education, agriculture and accessibility. Every team gets API credits and access to mentors from the organising partners.',
    eligibility: 'Teams of 2 to 4 students from any college and any year.',
    benefits: 'INR 3,00,000 prize pool, internship interviews for finalists, swag and certificates.',
    location: 'Bengaluru',
    mode: 'On-site',
    duration: '36 hours',
    stipend: 'INR 3,00,000 prize pool',
    deadlineIn: 9,
    applicationUrl: 'https://example.com/codecrafters/buildai-hackathon',
    source: 'CodeCrafters Community (sample)',
    skills: ['Python', 'Machine Learning', 'React', 'Node.js', 'Teamwork', 'Problem Solving'],
  },
  {
    title: 'OpenData Civic Hackathon',
    organization: 'CivicStack Foundation',
    category: 'hackathon',
    description:
      'Use publicly released city datasets to build tools that help citizens: transport planners, complaint trackers, air quality dashboards and more. Winning projects are considered for a pilot deployment with a partner municipality.',
    eligibility: 'Open to all students. Individual or team entries of up to 4 members.',
    benefits: 'INR 1,50,000 prize pool, pilot deployment opportunity, open source credit.',
    location: 'Remote',
    mode: 'Remote',
    duration: '48 hours',
    stipend: 'INR 1,50,000 prize pool',
    deadlineIn: 17,
    applicationUrl: 'https://example.com/civicstack/opendata-hackathon',
    source: 'CivicStack Foundation (sample)',
    skills: ['Python', 'Data Analysis', 'JavaScript', 'Tableau', 'Teamwork'],
  },
  {
    title: 'FinTech Innovation Hack',
    organization: 'Paysphere Labs',
    category: 'hackathon',
    description:
      'Prototype a solution for one of three problem statements in digital payments, fraud detection or credit scoring for thin-file customers. Sandbox APIs and anonymised datasets are provided to every registered team.',
    eligibility: 'Students in the 2nd year or above. Teams of up to 3.',
    benefits: 'INR 2,00,000 prize pool, fast-track internship interviews.',
    location: 'Remote',
    mode: 'Remote',
    duration: '24 hours',
    stipend: 'INR 2,00,000 prize pool',
    deadlineIn: 23,
    applicationUrl: 'https://example.com/paysphere/fintech-hack',
    source: 'Paysphere Labs (sample)',
    skills: ['Python', 'Machine Learning', 'SQL', 'Finance', 'Problem Solving'],
  },
  {
    title: 'IoT and Robotics Makeathon',
    organization: 'Circuit Society',
    category: 'hackathon',
    description:
      'A hardware-focused build weekend. Teams receive a microcontroller kit and sensors and must demonstrate a working prototype that solves a campus or community problem by the end of the event.',
    eligibility: 'Students from Electronics, Electrical, Mechanical, CS or Instrumentation branches.',
    benefits: 'Hardware kit to keep, INR 1,00,000 prize pool, lab access.',
    location: 'Chennai',
    mode: 'On-site',
    duration: '2 days',
    stipend: 'INR 1,00,000 prize pool',
    deadlineIn: 31,
    applicationUrl: 'https://example.com/circuit-society/makeathon',
    source: 'Circuit Society (sample)',
    skills: ['IoT', 'Robotics', 'C++', 'Python', 'Teamwork'],
  },

  // ---------------------------- COMPETITIONS -------------------------------
  {
    title: 'National Data Science Challenge',
    organization: 'Analytics Guild India',
    category: 'competition',
    description:
      'A four-week online modelling competition on a real anonymised retail dataset. Participants are ranked on a hidden test set, and the top ten finalists present their approach to a panel of practising data scientists.',
    eligibility: 'Any undergraduate or postgraduate student. Individual participation only.',
    benefits: 'INR 1,25,000 prize pool, leaderboard certificate, interview referrals.',
    location: 'Remote',
    mode: 'Remote',
    duration: '4 weeks',
    stipend: 'INR 1,25,000 prize pool',
    deadlineIn: 14,
    applicationUrl: 'https://example.com/analytics-guild/ds-challenge',
    source: 'Analytics Guild India (sample)',
    skills: ['Python', 'Machine Learning', 'Pandas', 'Statistics', 'NumPy'],
  },
  {
    title: 'Inter-College Case Study Competition',
    organization: 'Northline Consulting',
    category: 'competition',
    description:
      'Teams receive a real business problem and 72 hours to prepare a recommendation deck. Shortlisted teams present to a jury of consultants; the competition is a well-known route into consulting internships.',
    eligibility: 'Teams of 2 to 3 students from the same college, any degree.',
    benefits: 'INR 1,00,000 prize pool, internship interviews for the top 3 teams.',
    location: 'Delhi',
    mode: 'Hybrid',
    duration: '72 hours + finals',
    stipend: 'INR 1,00,000 prize pool',
    deadlineIn: 20,
    applicationUrl: 'https://example.com/northline/case-competition',
    source: 'Northline Consulting (sample)',
    skills: ['Business Analysis', 'Communication', 'Public Speaking', 'Excel', 'Teamwork'],
  },
  {
    title: 'Competitive Programming Grand Prix',
    organization: 'AlgoArena',
    category: 'competition',
    description:
      'A three-round algorithmic contest running over a month. Problems cover graphs, dynamic programming, number theory and data structures, with editorials published after every round so participants can learn from each problem.',
    eligibility: 'Open to all students from 1st year onwards.',
    benefits: 'INR 80,000 prize pool, contest rating, editorial access.',
    location: 'Remote',
    mode: 'Remote',
    duration: '3 rounds over 1 month',
    stipend: 'INR 80,000 prize pool',
    deadlineIn: 11,
    applicationUrl: 'https://example.com/algoarena/grand-prix',
    source: 'AlgoArena (sample)',
    skills: ['Algorithms', 'Data Structures', 'C++', 'Java', 'Problem Solving'],
  },

  // ---------------------------- COURSES ------------------------------------
  {
    title: 'Applied Machine Learning Certification',
    organization: 'Quantify Academy',
    category: 'course',
    description:
      'A twelve-week instructor-led certification covering supervised learning, model evaluation, feature engineering and deployment basics. Assessment is project-based: learners build and deploy three models over the course.',
    eligibility: 'Students comfortable with Python basics. Any degree or branch.',
    benefits: 'Graded certificate, three portfolio projects, placement assistance.',
    location: 'Remote',
    mode: 'Remote',
    duration: '12 weeks',
    stipend: 'Free for students (verified)',
    deadlineIn: 26,
    applicationUrl: 'https://example.com/quantify/applied-ml',
    source: 'Quantify Academy (sample)',
    skills: ['Python', 'Machine Learning', 'Pandas', 'NumPy', 'TensorFlow'],
  },
  {
    title: 'Full Stack Development Bootcamp',
    organization: 'Kairo Learning',
    category: 'course',
    description:
      'An intensive evening bootcamp that takes learners from HTML fundamentals to deploying a full MERN application. Weekly code reviews and a final group project make this suitable for students preparing for developer roles.',
    eligibility: 'Any student. No prior web development experience required.',
    benefits: 'Certificate, deployed capstone project, interview preparation sessions.',
    location: 'Remote',
    mode: 'Remote',
    duration: '16 weeks',
    stipend: 'INR 4,999 (student rate)',
    deadlineIn: 19,
    applicationUrl: 'https://example.com/kairo-learning/fullstack-bootcamp',
    source: 'Kairo Learning (sample)',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Node.js', 'SQL', 'Git'],
  },
  {
    title: 'Cloud Practitioner Preparation Course',
    organization: 'Stratos Academy',
    category: 'course',
    description:
      'A six-week guided course preparing students for an entry-level cloud certification. Includes hands-on labs on compute, storage, networking and billing, plus two full practice examinations.',
    eligibility: 'Students in any branch, 2nd year onwards.',
    benefits: 'Course certificate, lab credits, discounted exam voucher.',
    location: 'Remote',
    mode: 'Remote',
    duration: '6 weeks',
    stipend: 'Free with student email',
    deadlineIn: 38,
    applicationUrl: 'https://example.com/stratos-academy/cloud-practitioner',
    source: 'Stratos Academy (sample)',
    skills: ['Cloud Computing', 'AWS', 'Linux', 'Networking'],
  },
  {
    title: 'Data Visualisation with Power BI and Tableau',
    organization: 'Vector Analytics Institute',
    category: 'course',
    description:
      'A practical course on turning raw spreadsheets into dashboards that decision-makers actually use. Covers data modelling, chart selection, interactivity and storytelling with data.',
    eligibility: 'Open to all students. Basic spreadsheet knowledge helps.',
    benefits: 'Certificate, dashboard portfolio, dataset library access.',
    location: 'Remote',
    mode: 'Remote',
    duration: '5 weeks',
    stipend: 'INR 2,499 (student rate)',
    deadlineIn: 34,
    applicationUrl: 'https://example.com/vector-institute/data-viz',
    source: 'Vector Analytics Institute (sample)',
    skills: ['Power BI', 'Tableau', 'Excel', 'Data Analysis', 'SQL'],
  },

  // ---------------------------- WORKSHOPS ----------------------------------
  {
    title: 'Resume and Interview Preparation Workshop',
    organization: 'CareerBridge',
    category: 'workshop',
    description:
      'A two-day workshop on writing a technical resume that passes automated screening, followed by live mock interviews with feedback. Every participant leaves with a reviewed resume and a recorded practice interview.',
    eligibility: 'Pre-final and final year students of any degree.',
    benefits: 'Reviewed resume, recorded mock interview, hiring manager Q&A.',
    location: 'Remote',
    mode: 'Remote',
    duration: '2 days',
    stipend: 'Free',
    deadlineIn: 7,
    applicationUrl: 'https://example.com/careerbridge/resume-workshop',
    source: 'CareerBridge (sample)',
    skills: ['Communication', 'Public Speaking', 'Problem Solving'],
  },
  {
    title: 'Hands-on Deep Learning Workshop',
    organization: 'Nimbus AI Labs',
    category: 'workshop',
    description:
      'A one-day practical workshop where participants train an image classifier and a small language model from scratch on provided GPU notebooks. Theory is kept short; most of the day is spent writing code.',
    eligibility: 'Students who already know Python and basic machine learning concepts.',
    benefits: 'GPU notebook access, workshop certificate, code repository.',
    location: 'Bengaluru',
    mode: 'Hybrid',
    duration: '1 day',
    stipend: 'Free for students',
    deadlineIn: 13,
    applicationUrl: 'https://example.com/nimbus-ai/dl-workshop',
    source: 'Nimbus AI Labs (sample)',
    skills: ['Python', 'Deep Learning', 'PyTorch', 'TensorFlow', 'Machine Learning'],
  },

  // ---------------------------- FELLOWSHIP ---------------------------------
  {
    title: 'Undergraduate Research Fellowship in AI',
    organization: 'Institute of Computational Sciences',
    category: 'fellowship',
    description:
      'A funded one-year research fellowship for undergraduates who want to experience academic research. Fellows join a lab, co-author a paper submission and present at the annual institute symposium.',
    eligibility: 'Students in the 3rd year or above with a strong academic record and a research statement.',
    benefits: 'Monthly fellowship, conference travel support, publication mentorship.',
    location: 'Remote',
    mode: 'Hybrid',
    duration: '12 months',
    stipend: 'INR 20,000 / month',
    deadlineIn: 47,
    applicationUrl: 'https://example.com/ics/ug-research-fellowship',
    source: 'Institute of Computational Sciences (sample)',
    skills: ['Python', 'Machine Learning', 'Research Writing', 'Statistics', 'Deep Learning'],
  },

  // ---------------------------- CAREER PROGRAM -----------------------------
  {
    title: 'Early Careers Mentorship Programme',
    organization: 'CareerBridge',
    category: 'career-program',
    description:
      'A six-month structured mentorship programme matching students with working professionals in their target role. Includes monthly one-to-one sessions, a goal tracker and access to a private job referral board.',
    eligibility: 'Students in the 2nd year or above who can commit to two hours per month.',
    benefits: 'Dedicated mentor, referral board access, completion certificate.',
    location: 'Remote',
    mode: 'Remote',
    duration: '6 months',
    stipend: 'Free',
    deadlineIn: 42,
    applicationUrl: 'https://example.com/careerbridge/mentorship',
    source: 'CareerBridge (sample)',
    skills: ['Communication', 'Teamwork', 'Problem Solving'],
  },
];

export default { CATEGORIES, SKILLS, INTERESTS, OPPORTUNITIES, daysFromNow };
